name: CI workflow for siwtchbot Project
on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.14]
    steps:
      - name: Setup Go ${{ matrix.node }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.node }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -v
